- name: Upgrade all packages, excluding kernel
  become: true
  become_user: root
  yum:
    name: '*'
    state: latest
    exclude: kernel*

- name: installing some dependencies
  become: true
  become_user: root
  yum:
    name: "{{ item }}"
    state: present
  loop:
  - vim
  - jna
  - sysstat
  - libselinux-python
  - lsof
