- name: install cassandra package
  become: true
  become_user: root
  yum:
    name: cassandra
    state: present

- name: configuring cassandra
  become: true
  become_user: root
  template:
    source: cassandra.yaml.j2
    dest: '/etc/cassandra/conf/cassandra.yaml'
  notify:
    - Start Cassandra
    - Enable Cassandra
