- name: install cassandra package
  become: true
  become_user: root
  yum:
    name: cassandra
    state: present
  tags:
    - cassandra

- name: configuring cassandra
  become: true
  become_user: root
  template:
    src: cassandra.yaml.j2
    dest: '/etc/cassandra/conf/cassandra.yaml'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Start Cassandra
    - Enable Cassandra
  tags:
    - cassandra
