- name: installing Datastax cassandra
  yum:
    package: cassandra
    state: present

- name: configuring cassandra
  template:
    source: cassandra.yaml.j2
    dest: '/etc/cassandra/conf/cassandra.yaml'
  notify:
    - Start Cassandra
    - Enable Cassandra
