- name: install cassandra package
  become: true
  become_user: root
  yum:
    name: cassandra
    state: present
  tags:
    - cassandra

- name: Adjusting sysctl parameter
  become: true
  become_user: root
  sysctl:
    name: vm.max_map_count
    value: 1048575
    sysctl_set: yes
    state: present
    reload: yes

- name: Adjusting sysctl parameter
  become: true
  become_user: root
  sysctl:
    name: fs.file-max
    value: 2097152
    sysctl_set: yes
    state: present
    reload: yes

- name: Adjusting sysctl parameter
  become: true
  become_user: root
  sysctl:
    name: vm.swappiness
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: configuring cassandra
  become: true
  become_user: root
  template:
    src: cassandra.yaml.j2
    dest: '/etc/cassandra/conf/cassandra.yaml'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Cassandra Restart
  tags:
    - cassandra

- name: Datadir Ownership
  become: true
  become_user: root
  file:
    path: "{{ config.data_file_directories }}"
    state: directory
    recurse: yes
    owner: cassandra
    group: cassandra
    mode: '0774'

- name: Hintsdir Ownership
  become: true
  become_user: root
  file:
    path: /hints
    state: directory
    recurse: yes
    owner: cassandra
    group: cassandra
    mode: '0774'

- name: Selinux Datadir
  become: true
  become_user: root
  sefcontext:
    target: "{{ config.data_file_directories }}"
    setype: httpd_sys_script_exec_t
    state: present

- name: Selinux Hintsdir
  become: true
  become_user: root
  sefcontext:
    target: '/hints'
    setype: httpd_sys_script_exec_t
    state: present


- name: Enable Cassandra
  become: true
  become_user: root
  service:
    name: cassandra
    enabled: true
  tags:
    - cassandra

- name: Start Cassandra
  become: true
  become_user: root
  service:
    name: cassandra
    state: started
  tags:
    - cassandra
