- name: install cassandra package
  become: true
  become_user: root
  yum:
    name: cassandra
    state: present
  tags:
    - cassandra

- name: Adjusting sysctl parameter
  sysctl:
    name: vm.max_map_count
    value: 1048575
    sysctl_set: yes
    state: present
    reload: yes

- name: Adjusting sysctl parameter
  sysctl:
    name: fs.file-max
    value: 2097152
    sysctl_set: yes
    state: present
    reload: yes

- name: Adjusting sysctl parameter
  sysctl:
    name: vm.swappiness
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: configuring cassandra
  become: true
  become_user: root
  template:
    src: cassandra.yaml.j2
    dest: '/etc/cassandra/conf/cassandra.yaml'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Start Cassandra
    - Enable Cassandra
  tags:
    - cassandra
