---
# tasks file for cassandra
- name: Include task list for dependiences startup
  include_tasks: dependencies.yml
  tags:
    - dependencies

- name: Include task list for oracle container startup
  include_tasks: repositories.yml
  tags:
    - repositories
