---
# tasks file for cassandra
- name: Include task list for dependiences startup
  include_tasks: dependencies.yml
  tags:
    - dependencies

- name: Include task list for repo setup
  include_tasks: repositories.yml
  tags:
    - repositories

- name: Include task list for firewall setup
  include_tasks: firewall.yml
  tags:
    - firewall

- name: Include task list installing cassandra
  include_tasks: install-cassandra.yml
  tags:
    - cassandra

- name: Include tasks for post deployment jobs
  include_tasks: post-deploy.yml
  tags:
    - post
