---
# tasks file for cassandra
- name: Include task list for dependiences startup
  include_tasks: dependiences.yml
  tags:
    - dependiences

- name: Include task list for oracle container startup
  include_tasks: repostitories.yml
  tags:
    - repositiories
