---
# handlers file for cassandra
- name: Datadir Ownership
  become: true
  become_user: root
  file:
    path: "{{ config.data_file_directories }}"
    state: directory
    recurse: yes
    owner: cassandra
    group: cassandra
    mode: '0664'

- name: Start Cassandra
  systemd:
    name: cassandra
    state: restarted

- name: Enable Cassandra
  systemd:
    name: cassandra
    state: enabled
