---
# handlers file for cassandra
- name: Datadir Ownership
  file:
    path: "{{ config.data_file_directories }}"
    state: directory
    recurse: yes
    owner: cassandra
    group: cassandra

- name: Start Cassandra
  systemd:
    name: cassandra
    state: restarted

- name: Enable Cassandra
  systemd:
    name: cassandra
    state: enabled
